#!/bin/sh
# The files to obfuscate
uglifyjs \
./client/classes/extends/string.js \
./client/classes/extends/object.js \
./client/classes/template.js \
./client/classes/menu.js \
./client/classes/postwindow.js \
./client/classes/buttons.js \
./client/classes/settings.js \
./client/classes/board.js \
./client/classes/screens.js \
./client/classes/connection.js \
./client/classes/login.js \
./client/classes/post.js \
./client/functions/device.js \
./client/functions/form.js \
./client/functions/log.js \
./client/functions/animation.js \
./client/static/language.js \
./client/static/config.js \
./client/static/templates.js \
./client/vendor/socket.io/socket.io.js \
./client/vendor/cubiq/add2home.js \
./client/vendor/jquery/jquery.min.js \
./client/vendor/jquery/jquery-ui.min.js \
./client/vendor/jquery/jquery.pstrength.js \
./client/vendor/jquery/jquery.color.js \
./client/vendor/jquery/jquery-ui.touchpunch.js \
./client/vendor/jquery/jquerytinysort.js \
./client/vendor/crypto/rollups/sha3.js \
./client/vendor/crypto/rollups/aes.js \
./client/vendor/apprise/apprise-v2.js \
./client/init/window.js \
./client/init/footer-navigation.js \
./client/init/board.js \
./client/init/ui.js \
./client/init/messaging.js \
./client/init/loader.js \
./client/interactions/board.js \
./client/interactions/screen.js \
./client/interactions/footer-navigation.js \
./client/interactions/ui.js \
./client/interactions/window.js \
./client/main.js \
-c -m  -o ./public/js/client.js
